# 一组storage服务器，包含两个containers

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fastdfs-storage
spec:
  replicas: 2
  selector:
    matchLabels:
      server: fastdfs-storage-server
  template:
    metadata:
      labels:
        server: fastdfs-storage-server
    spec:
      containers:
        - name: fastdfs-storage-server
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: etc
              mountPath: /etc/fdfs
          image: xyparacrim/fastdfs:k8s-slim
          command: ["xpc_fdfs_storage_full.sh"]
          ports:
            - containerPort: 23000
            - containerPort: 8080
      volumes:
        - name: etc
          hostPath:
            path: /Users/yanjiaxun/IdeaProjects/leet-code/middleware/fastdfs/k8s/etc
  serviceName: fastdfs-storage-service