#apiVersion: v1
#kind: Service
#metadata:
#  name: mysql-test-service
#spec:
#  selector:
#    app: mysql
#  ports:
#    - port: 3306
#  clusterIP: None
#
#---
#apiVersion: apps/v1
#kind: StatefulSet
#metadata:
#  name: mysql-test
#spec:
#  replicas: 2
#  selector:
#    matchLabels:
#      app: mysql
#  serviceName: mysql-test-service
#  template:
#    metadata:
#      labels:
#        app: mysql
#    spec:
#      containers:
#        - name: mysql
#          image: mysql:latest
#          env:
#            - name: MYSQL_ROOT_PASSWORD
#              value: "110120"
#            - name: POD_NAME
#              valueFrom:
#                fieldRef:
#                  apiVersion: v1
#                  fieldPath: metadata.name
#            - name: HOSTNAME
#              value: $(POD_NAME).mysql-test-service
#          ports:
#            - containerPort: 3306
#          volumeMounts:
#            - name: data
#              mountPath: /var/lib/mysql
#              subPathExpr: $(POD_NAME)
#      volumes:
#        - name: data
#          persistentVolumeClaim:
#            claimName: mysql-claim
#---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-shell
spec:
  containers:
    - name: mysql-shell-container
      image: xyparacrim/mysql-shell:v1
      command: ["tail", "-f", "/dev/null"]
